line-length = 120

lint.select = [
  "E",   # pycodestyle
  "F",   # pyflakes
  "I",   # isort
]

[lint.per-file-ignores]
"__init__.py" = [
    "F401",     # <module> imported but unused
]

"tests/*" = [
    # Line too long
    "E501",
]
